### ISSUE TITLE
Please make sure font used on your homepage is readable.

### ISSUE THREAD

**Issue by jelkner** [Henry-H08/website#2]
I'm not sure what you see when you visit your homepage, but this is what I see:

![henryhomepage](https://github.com/Henry-H08/website/assets/819114/9eb36676-a53c-44c3-88f1-5b665730f1b2)

It's a bit challenging to navigate.  Please fix.

**Comment by Henry-H08** [comment]
that is very strange mine looks like this 
<img width="1440" alt="Screen Shot 2023-12-04 at 8 51 05 AM" src="https://github.com/Henry-H08/website/assets/143623813/d4cc2d52-6a9a-46b0-b68e-575bc975a0ee">
